### ISSUE TITLE
Set Behat and Drupal driver as dependecies on composer.json

### ISSUE THREAD

**Issue by tassoskoutlas** [cameronandwilding/CWTest_Behat#2]
Currently behat and drupal driver are installed as part of the post installation script. Consider moving these to the dependencies section of `compose.json`.

**Comment by brendanmacdonald** [comment]
I'm not sure if we can do this. 
We need Behat to be installed inside the framework for it to work correctly.
If we put behat inside the first composer file, then behat is installed outside of the framework, which breaks the links the framework expects.
Perhaps we can have a chat about this, and come up with a solution?

**Comment by ericgsmith** [comment]
These have been moved to dependencies of the project composer.json :)
