### ISSUE TITLE
Bootstrap script is not context independent

### ISSUE THREAD

**Issue by itarato** [cameronandwilding/CWTest_Behat#46]
Running the https://github.com/cameronandwilding/CWTest_Behat/blob/master/bin/cwtest-bootstrap.sh script fails if it runs outside of its directory. To make it flexible it shouldn't depend on the caller path.

**Comment by brendanmacdonald** [comment]
Peter - I got this working - is that the type of thing you were looking for?

#!/bin/sh

SCRIPTDIR=$(cd $(dirname "$0") && pwd)

# Make directories.

mkdir $SCRIPTDIR/../Servers
mkdir $SCRIPTDIR/../Results
mkdir $SCRIPTDIR/../Results/Behat
mkdir $SCRIPTDIR/../Results/Behat/screenshots

# Download selenium

wget http://selenium-release.storage.googleapis.com/2.49/selenium-server-standalone-2.49.1.jar -O ./../Servers/selenium.jar

# Copy over the sample files directory.

BIN_DIR="$(dirname $(readlink $BASH_SOURCE))"
cp  -nR ${SCRIPTDIR}/${BIN_DIR}/../Sample_Files/\* ${SCRIPTDIR}/../
cp -R ${SCRIPTDIR}/${BIN_DIR}/../README.md ${SCRIPTDIR}/../
cp -R ${SCRIPTDIR}/${BIN_DIR}/../.gitignore ${SCRIPTDIR}/../
cp ${SCRIPTDIR}/${BIN_DIR}/../Sample_Files/Behat/run-behat.sh ${SCRIPTDIR}/../Behat

**Comment by itarato** [comment]
@brendanmacdonald yup, the rest could be the same, just wherever you address a directory you use the absolute path (${SCRIPTDIR}) to begin with

**Comment by itarato** [comment]
![](http://gifimage.net/wp-content/uploads/2017/06/celebration-gif-15.gif)
