### ISSUE TITLE
Where should I put project-specific contexts and features?

### ISSUE THREAD

**Issue by andriokha** [cameronandwilding/CWTest_Behat#60]
Hi,

I saw a presentation on this at DrupalCamp London and I've been meaning to try it out ever since! Thanks for all your hard work.

I'm trying to write my first test and I'm not sure where to put my custom contexts and features. I found [this video](http://vimeo.com/161773442) which shows a `run-behat.sh` that copies files from the `Behat_Test_Files` directory... but there's no hint of that in this repo (or I'm blind!).

What's the recommended approach here?

Thanks

**Comment by brendanmacdonald** [comment]
![image](https://cloud.githubusercontent.com/assets/11874330/16617137/d7406fd8-4379-11e6-9199-3752f48db53e.png)

Hi,

Thanks very much for your question. Glad you are trying this out.
In the screenshot above (hopefully you are seeing the same thing on your setup):
1 - this is where your .feature files go
2. this is where your custom context files go.
3. this is where your page definitions go.

The video you are referring to is slightly out of date - we no longer use the Behat_Test_Files directory.

Any more questions, please ask.

**Comment by andriokha** [comment]
Wow, thanks for such a quick reply! Does that mean you just store pretty much everything in source control? When I saw the old video, I imagined storing Behat_Test_Files in source control, but only adding the composer.json for CWTest_Behat... is something like that still possible with the approach above?

Thanks again

**Comment by brendanmacdonald** [comment]
With the current version, most files will get stored in source control.
The .gitignore file will prevent the large vendor folder from being added, along with the Results & Servers folder. However, you can customise this to your needs so that you have in source control exactly what you need.

It looks like I'll need to update that video :-)

**Comment by andriokha** [comment]
Thanks for the clarification, that's absolutely perfect!
